import express from "express";
import companyRoutes from "./companyRoutes";
import auditLogsRoutes from "./auditLogsRoutes";
import certificatesRoutes from "./certificatesRoutes";
import companyAdminsRoutes from "./companyAdminsRoutes";
import companyStatisticsRoutes from "./companyStatisticsRoutes";
import courseCategoriesRoutes from "./courseCategoriesRoutes";
import courseEnrollmentsRoutes from "./courseEnrollmentsRoutes";
import courseModulesRoutes from "./courseModulesRoutes";
import courseReviewsRoutes from "./courseReviewsRoutes";
import coursesRoutes from "./coursesRoutes";
import departmentsRoutes from "./departmentsRoutes";
import employeeGroupMembersRoutes from "./employeeGroupMembersRoutes";
import employeeGroupsRoutes from "./employeeGroupsRoutes";
import employeesRoutes from "./employeesRoutes";
import lessonMaterialsRoutes from "./lessonMaterialsRoutes";
import lessonProgressRoutes from "./lessonProgressRoutes";
import lessonsRoutes from "./lessonsRoutes";
import notificationsRoutes from "./notificationsRoutes";
import questionOptionsRoutes from "./questionOptionsRoutes";
import rootAdminsRoutes from "./rootAdminsRoutes";
import subscriptionPlansRoutes from "./subscriptionPlansRoutes";
import testAnswersRoutes from "./testAnswersRoutes";
import testAttemptsRoutes from "./testAttemptsRoutes";
import testQuestionsRoutes from "./testQuestionsRoutes";
import testsRoutes from "./testsRoutes";

const router = express.Router();

router.use("/companies", companyRoutes);
router.use("/audit-logs", auditLogsRoutes);
router.use("/certificates", certificatesRoutes);
router.use("/company-admins", companyAdminsRoutes);
router.use("/company-statistics", companyStatisticsRoutes);
router.use("/course-categories", courseCategoriesRoutes);
router.use("/course-enrollments", courseEnrollmentsRoutes);
router.use("/course-modules", courseModulesRoutes);
router.use("/course-reviews", courseReviewsRoutes);
router.use("/courses", coursesRoutes);
router.use("/departments", departmentsRoutes);
router.use("/employee-group-members", employeeGroupMembersRoutes);
router.use("/employee-groups", employeeGroupsRoutes);
router.use("/employees", employeesRoutes);
router.use("/lesson-materials", lessonMaterialsRoutes);
router.use("/lesson-progress", lessonProgressRoutes);
router.use("/lessons", lessonsRoutes);
router.use("/notifications", notificationsRoutes);
router.use("/question-options", questionOptionsRoutes);
router.use("/root-admins", rootAdminsRoutes);
router.use("/subscription-plans", subscriptionPlansRoutes);
router.use("/test-answers", testAnswersRoutes);
router.use("/test-attempts", testAttemptsRoutes);
router.use("/test-questions", testQuestionsRoutes);
router.use("/tests", testsRoutes);

export default router;